name: Rails
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-local-rails-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check prerequisites
        run: |
          python -V
          pip -V
          pip install -r ./.github/workflows/requirements.txt
          python ./.github/workflows/try_issues.py
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1 # https://github.com/ruby/setup-ruby
        with:
          ruby-version: 2.7 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically, any step doing bundle install (for the root Gemfile) or gem install bundler can be removed with bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: |
          yarn install
      - name: Run local RSpec tests
        run: |
          RAILS_ENV=test bundle exec rails db:migrate
          bundle exec rspec spec/
      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
      - name: Echo file changes
        run: |
          echo Changed files: ${{ steps.get_file_changes.outputs.files }}
      - name: Run lint
        uses: dorner/lint-action@v1.3.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rubocop_bundler: true
          auto_fix: true
          rubocop_bundler_args: -R --fail-level C ${{ steps.get_file_changes.outputs.files}}
#        script:
#          - BASE=$(git merge-base origin/master HEAD)
#          - >
#            git diff --name-only --diff-filter=d ${BASE} HEAD
#            | tee /dev/stderr
#            | xargs --no-run-if-empty bundle exec rubocop --force-exclusion --parallel
#        except:
#          refs: [ master ]
      - name: Run exercise automation
        run: |
          ./.github/workflows/exercise_automation
